# -*- coding: utf-8 -*-
"""csv_matplotlib

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ns8gjPcQSdnVRh2pwm_gjeDIFDAH7Rax
"""

## Program to plot list data from CSV file with the matplotlib package
import matplotlib.pyplot as plt
import csv

def main():
  #create list to hold heights of each bar
  values = []
  #create list for categories
  categories = []

  #open the csv file
  with open('data.csv', 'r') as file:
    #create reader object
    reader = csv.reader(file)
    #skip header row
    next(reader)
    #iterate through each column
    for row in reader:
      #add categories to list
      categories.append(row[0])
      #add values to list
      values.append(int(row[1]))

  #create bar chart
  plt.bar(categories, values, color=('#f2737c','#fde77a','#fc365a','#a6f9a0','#a0ebf9'))
  #x label
  plt.xlabel('Category')
  #y label
  plt.ylabel('Value')
  #title
  plt.title("Fruit Distribution")
  #display bar chart
  plt.show()

#call main
if __name__ == "__main__":
  main()