# -*- coding: utf-8 -*-
"""csv_file

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ClP_m8W4Hup5h6BtrV4S2JDclxvLfMV3
"""

## Program to create lists objects by reading line by line from a CSV file
#import csv
import csv

#list for categories
categories = []
#list for values
values = []

#open file and read
with open('data.csv', 'r') as file:
  #csv.reader() to read CSV file line by line
  reader = csv.reader(file)
  #next(reader) skips the header row if the CSV file has one
  next(reader)
  #iterate through each column
  for row in reader:
    #first column from the CSV is appended to categories list
    categories.append(row[0])
    #second column is appended to values list after converting it to an integer
    values.append(int(row[1]))

#print the lists
print("Categories List:", categories)
print("Values List:", values)