# -*- coding: utf-8 -*-
"""expense_pie_chart

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TpE1EHnGA2gjM2P58SXFdsaanGugUyj1
"""

import matplotlib.pyplot as plt

def main():
  #create values for the amount of fruit
  values = [25,30,15,10,20]
  #create labels
  fruits = ['Apples','Bananas','Cherries','Dates','Berries']

  #create pie chart
  plt.pie(values, colors=['#ff9999','#66b3fe','#99ff99','#274ae9','#c2c2f0'], labels=fruits, autopct='%1.1f%%')

  #create title
  plt.title("Fruit Distribution")

  #show pie chart
  plt.show()

#call main function
if __name__ == '__main__':
  main()