# -*- coding: utf-8 -*-
"""two_dimensional_list

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kD7OdCsydsMzG_Of_E9SxbzlCMcMWQv1
"""

# write a program to create a 2 dimensional list with random() function
import random

#define the number of rows, columns, and the range of random numbers
rows = 3 #rows
cols = 4 #columns
lower_bound = 1 #min random number
upper_bound = 100 #max random number

#create the 2D matrix using nested loops
random_matrix = []
for i in range(rows):
    row = [] #create an empty list for each row
    for j in range(cols):
        row.append(random.randint(lower_bound, upper_bound)) #add a random number to the row
    random_matrix.append(row) #add the row to the matrix

#printing the matrix
print('Random Matrix:')
for row in random_matrix:
    print(row)